server:
  host: "0.0.0.0"
  port: "8000"
  timeout: 15

clients:
  - username: "yuta"
    password: "verystronkone"
    homeserverurl: "dendrite.maibaloc.com"
    clienttype: "matrix"

nluclients:
  - clienttype: "diaglogflow"
    projectid: "yuta-seig"
    sessionid: "test"

