clients:
  - username: "yuta"
    password: "verystronkone"
    homeserverurl: "dendrite.maibaloc.com"
    clienttype: "matrix"

nluclients:
  - service: diaglogflow
    projectID: "yuta-seig"
    sessionID: "test"

server:
  host: "0.0.0.0"
  port: "8000"
  timeout: 15
